[2017-05-15 13:33:08] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:33:09] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/cuisine/5/1" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/cuisine/5/1\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/cuisine/5/1\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:33:09] application.ERROR: No route found for "GET /recipe/cuisine/5/1" [] []
[2017-05-15 13:33:09] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:33:09] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:33:09] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:33:09] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 13:33:09] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:33:09] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /recipe/update/5" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /recipe/update/5\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/update/5\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:33:09] application.ERROR: No route found for "POST /recipe/update/5" [] []
[2017-05-15 13:33:09] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:33:09] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:33:09] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:33:53] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:33:53] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/cuisine/5/1" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/cuisine/5/1\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/cuisine/5/1\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:33:53] application.ERROR: No route found for "GET /recipe/cuisine/5/1" [] []
[2017-05-15 13:33:53] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:33:53] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:33:53] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:33:53] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 13:33:53] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:33:53] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /recipe/update/5" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /recipe/update/5\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/update/5\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:33:53] application.ERROR: No route found for "POST /recipe/update/5" [] []
[2017-05-15 13:33:53] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:33:53] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:33:53] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:34:17] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:34:17] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/cuisine/5/1" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/cuisine/5/1\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/cuisine/5/1\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:34:17] application.ERROR: No route found for "GET /recipe/cuisine/5/1" [] []
[2017-05-15 13:34:17] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:34:17] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:34:17] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:34:17] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 13:34:17] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:34:17] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /recipe/update/5" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /recipe/update/5\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/update/5\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:34:17] application.ERROR: No route found for "POST /recipe/update/5" [] []
[2017-05-15 13:34:17] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:34:17] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:34:17] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:35:15] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:35:15] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/british/5/1" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/british/5/1\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/british/5/1\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:35:15] application.ERROR: No route found for "GET /recipe/british/5/1" [] []
[2017-05-15 13:35:15] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:35:15] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:35:15] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:35:15] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 13:35:15] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:35:15] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /recipe/update/5" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /recipe/update/5\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/update/5\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:35:15] application.ERROR: No route found for "POST /recipe/update/5" [] []
[2017-05-15 13:35:15] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:35:15] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:35:15] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:35:31] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:35:31] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/british/5/1" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/british/5/1\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/british/5/1\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:35:31] application.ERROR: No route found for "GET /recipe/british/5/1" [] []
[2017-05-15 13:35:31] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:35:31] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:35:31] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:35:31] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 13:35:31] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:35:32] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /recipe/update/5" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /recipe/update/5\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/update/5\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:35:32] application.ERROR: No route found for "POST /recipe/update/5" [] []
[2017-05-15 13:35:32] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:35:32] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:35:32] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:35:54] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:35:54] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/british/5/1" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/british/5/1\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/british/5/1\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:35:54] application.ERROR: No route found for "GET /recipe/british/5/1" [] []
[2017-05-15 13:35:54] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:35:54] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:35:54] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:35:54] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 13:35:54] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:35:54] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /recipe/update/5" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /recipe/update/5\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/update/5\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:35:54] application.ERROR: No route found for "POST /recipe/update/5" [] []
[2017-05-15 13:35:54] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:35:54] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:35:54] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:37:03] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:37:03] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:37:03] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:37:03] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:37:03] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 13:37:03] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:37:03] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "POST /recipe/update/5" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /recipe/update/5\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/update/5\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:37:03] application.ERROR: No route found for "POST /recipe/update/5" [] []
[2017-05-15 13:37:03] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:37:03] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:37:03] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:38:47] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:39:15] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:39:17] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:39:41] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 131 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:131)"} []
[2017-05-15 13:39:49] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 131 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:131)"} []
[2017-05-15 13:40:17] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:48:13] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:48:15] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:49:05] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:49:21] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:50:37] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 131 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:131)"} []
[2017-05-15 13:50:38] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 131 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:131)"} []
[2017-05-15 13:51:09] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 131 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:131)"} []
[2017-05-15 13:52:40] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 131 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:131)"} []
[2017-05-15 13:52:43] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 131 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:131)"} []
[2017-05-15 13:53:31] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 131 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:131)"} []
[2017-05-15 13:54:33] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 131 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:131)"} []
[2017-05-15 13:54:35] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 131 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:131)"} []
[2017-05-15 13:54:53] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 132 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:132)"} []
[2017-05-15 13:55:10] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 131 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:131)"} []
[2017-05-15 13:55:13] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 131 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:131)"} []
[2017-05-15 13:55:51] application.ERROR: Uncaught Exception ParseError: "syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION)" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 130 {"exception":"[object] (ParseError(code: 0): syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:130)"} []
[2017-05-15 13:57:00] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM recipe WHERE id=?' with params [1]:  SQLSTATE[HY000]: General error: 1 no such table: recipe (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 58 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM recipe WHERE id=?' with params [1]:\n\nSQLSTATE[HY000]: General error: 1 no such table: recipe at /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:58, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1 no such table: recipe at /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1 no such table: recipe at /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77)"} []
[2017-05-15 13:57:00] application.ERROR: An exception occurred while executing 'SELECT * FROM recipe WHERE id=?' with params [1]:  SQLSTATE[HY000]: General error: 1 no such table: recipe [] []
[2017-05-15 13:57:00] application.ERROR: #0 /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM r...', Array) #2 /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM r...', Array, Array) #3 /Users/edweld/Documents/projects2017/gousto/src/App/Service/RecipeService.php(21): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM r...', Array) #4 /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php(44): App\Service\RecipeService->fetchOneById(1) #5 [internal function]: App\Controller\RecipeController->fetchOneById(1) #6 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #11 {main} [] []
[2017-05-15 13:57:12] application.CRITICAL: Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM recipe WHERE id=?' with params [1]:  SQLSTATE[HY000]: General error: 1 no such table: recipe (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php line 58 {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing 'SELECT * FROM recipe WHERE id=?' with params [1]:\n\nSQLSTATE[HY000]: General error: 1 no such table: recipe at /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:58, Doctrine\\DBAL\\Driver\\PDOException(code: HY000): SQLSTATE[HY000]: General error: 1 no such table: recipe at /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:79, PDOException(code: HY000): SQLSTATE[HY000]: General error: 1 no such table: recipe at /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77)"} []
[2017-05-15 13:57:12] application.ERROR: An exception occurred while executing 'SELECT * FROM recipe WHERE id=?' with params [1]:  SQLSTATE[HY000]: General error: 1 no such table: recipe [] []
[2017-05-15 13:57:12] application.ERROR: #0 /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'SELECT * FROM r...', Array) #2 /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(510): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM r...', Array, Array) #3 /Users/edweld/Documents/projects2017/gousto/src/App/Service/RecipeService.php(21): Doctrine\DBAL\Connection->fetchAssoc('SELECT * FROM r...', Array) #4 /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php(44): App\Service\RecipeService->fetchOneById(1) #5 [internal function]: App\Controller\RecipeController->fetchOneById(1) #6 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array) #7 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #8 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #9 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #10 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #11 {main} [] []
[2017-05-15 13:58:57] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 13:58:57] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 13:58:57] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 13:58:57] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 13:58:57] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 13:58:57] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:00:23] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 14:00:23] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 14:00:23] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:00:23] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:00:24] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:00:24] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:01:35] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 14:01:35] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 14:01:35] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:01:35] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:01:35] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:01:35] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:02:33] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 14:02:33] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 14:02:33] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:02:33] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:02:33] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:02:33] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:03:27] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 14:03:27] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 14:03:27] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:03:27] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:03:27] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:03:27] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:04:24] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 14:04:24] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 14:04:24] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:04:24] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:04:24] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:04:24] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:04:37] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 14:04:37] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 14:04:37] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:04:37] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:04:37] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:04:37] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:06:27] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 14:06:27] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 14:06:27] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:06:27] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:06:27] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:06:27] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:07:30] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 14:07:30] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 14:07:30] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:07:30] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:07:30] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:07:30] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:08:16] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 14:08:16] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 14:08:16] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:08:16] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:08:16] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:08:16] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:12:19] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 14:12:19] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 14:12:19] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:12:19] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:12:19] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:12:20] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:14:15] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/cusine/british/5/1" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/cusine/british/5/1\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/cusine/british/5/1\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 14:14:15] application.ERROR: No route found for "GET /recipe/cusine/british/5/1" [] []
[2017-05-15 14:14:15] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:19:50] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:19:50] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:19:50] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:25:22] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:25:22] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:25:22] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:27:13] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "POST /recipe/cuisine/british/5/2": Method Not Allowed (Allow: GET, OPTIONS) (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"POST /recipe/cuisine/british/5/2\": Method Not Allowed (Allow: GET, OPTIONS) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-05-15 14:27:13] application.ERROR: No route found for "POST /recipe/cuisine/british/5/2": Method Not Allowed (Allow: GET, OPTIONS) [] []
[2017-05-15 14:27:13] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:27:28] application.ERROR: Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: No route found for "POST /recipe/update": Method Not Allowed (Allow: GET, OPTIONS) (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 129 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException(code: 0): No route found for \"POST /recipe/update\": Method Not Allowed (Allow: GET, OPTIONS) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:129, Symfony\\Component\\Routing\\Exception\\MethodNotAllowedException(code: 0):  at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:97)"} []
[2017-05-15 14:27:28] application.ERROR: No route found for "POST /recipe/update": Method Not Allowed (Allow: GET, OPTIONS) [] []
[2017-05-15 14:27:28] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:28:06] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:28:07] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:28:07] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:30:20] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:30:20] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 113 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:113)"} []
[2017-05-15 14:30:20] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 126 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:126)"} []
[2017-05-15 14:30:53] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:32:42] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 154 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:154)"} []
[2017-05-15 14:33:05] application.ERROR: Uncaught Exception Error: "Class 'App\Exception\RecipeInvalidException' not found" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 156 {"exception":"[object] (Error(code: 0): Class 'App\\Exception\\RecipeInvalidException' not found at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:156)"} []
[2017-05-15 14:35:03] application.ALERT: Fatal Error (E_ERROR): Class 'App\Exception\Exception' not found {"code":1,"message":"Class 'App\\Exception\\Exception' not found","file":"/Users/edweld/Documents/projects2017/gousto/src/App/Exception/RecipeInvalidException.php","line":11} []
[2017-05-15 14:52:07] application.ERROR: Uncaught Exception TypeError: "Argument 1 passed to App\Controller\RecipeController::getValidatedRecipeDataFromRequest() must be an instance of Symfony\Component\HttpFoundation\Request, array given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php on line 99" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 141 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Controller\\RecipeController::getValidatedRecipeDataFromRequest() must be an instance of Symfony\\Component\\HttpFoundation\\Request, array given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php on line 99 at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:141)"} []
[2017-05-15 14:52:15] application.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException: No route found for "GET /recipe/" (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /recipe/\" at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/EventListener/RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/recipe/\". at /Users/edweld/Documents/projects2017/gousto/vendor/symfony/routing/Matcher/UrlMatcher.php:98)"} []
[2017-05-15 14:52:15] application.ERROR: No route found for "GET /recipe/" [] []
[2017-05-15 14:52:15] application.ERROR: #0 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #3 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(129): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) #4 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #5 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #6 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #7 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #8 {main} [] []
[2017-05-15 14:52:15] application.ERROR: Uncaught Exception TypeError: "Argument 1 passed to App\Controller\RecipeController::getValidatedRecipeDataFromRequest() must be an instance of Symfony\Component\HttpFoundation\Request, array given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php on line 99" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 141 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Controller\\RecipeController::getValidatedRecipeDataFromRequest() must be an instance of Symfony\\Component\\HttpFoundation\\Request, array given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php on line 99 at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:141)"} []
[2017-05-15 14:52:15] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 115 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:115)"} []
[2017-05-15 14:52:15] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 128 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:128)"} []
[2017-05-15 14:52:38] application.ERROR: Uncaught Exception TypeError: "Argument 1 passed to App\Controller\RecipeController::getValidatedRecipeDataFromRequest() must be an instance of Symfony\Component\HttpFoundation\Request, array given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php on line 99" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 141 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Controller\\RecipeController::getValidatedRecipeDataFromRequest() must be an instance of Symfony\\Component\\HttpFoundation\\Request, array given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php on line 99 at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:141)"} []
[2017-05-15 14:52:38] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 115 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:115)"} []
[2017-05-15 14:52:38] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 128 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:128)"} []
[2017-05-15 14:53:29] application.ERROR: Uncaught Exception TypeError: "Argument 1 passed to App\Controller\RecipeController::getValidatedRecipeDataFromRequest() must be an instance of Symfony\Component\HttpFoundation\Request, array given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php on line 99" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 142 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Controller\\RecipeController::getValidatedRecipeDataFromRequest() must be an instance of Symfony\\Component\\HttpFoundation\\Request, array given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php on line 99 at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:142)"} []
[2017-05-15 14:53:29] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 116 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:116)"} []
[2017-05-15 14:53:29] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 129 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:129)"} []
[2017-05-15 14:53:34] application.ERROR: Uncaught Exception TypeError: "Argument 1 passed to App\Controller\RecipeController::getValidatedRecipeDataFromRequest() must be an instance of Symfony\Component\HttpFoundation\Request, array given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php on line 99" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 142 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Controller\\RecipeController::getValidatedRecipeDataFromRequest() must be an instance of Symfony\\Component\\HttpFoundation\\Request, array given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php on line 99 at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:142)"} []
[2017-05-15 14:53:37] application.ERROR: Uncaught Exception TypeError: "Argument 1 passed to App\Controller\RecipeController::getValidatedRecipeDataFromRequest() must be an instance of Symfony\Component\HttpFoundation\Request, array given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php on line 99" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 142 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Controller\\RecipeController::getValidatedRecipeDataFromRequest() must be an instance of Symfony\\Component\\HttpFoundation\\Request, array given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php on line 99 at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:142)"} []
[2017-05-15 14:54:26] application.ERROR: Uncaught Exception TypeError: "Argument 2 passed to Doctrine\DBAL\Connection::update() must be of the type array, null given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Service/RecipeService.php on line 60" at /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 652 {"exception":"[object] (TypeError(code: 0): Argument 2 passed to Doctrine\\DBAL\\Connection::update() must be of the type array, null given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Service/RecipeService.php on line 60 at /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:652)"} []
[2017-05-15 14:54:32] application.ERROR: Uncaught Exception TypeError: "Argument 2 passed to Doctrine\DBAL\Connection::update() must be of the type array, null given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Service/RecipeService.php on line 60" at /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 652 {"exception":"[object] (TypeError(code: 0): Argument 2 passed to Doctrine\\DBAL\\Connection::update() must be of the type array, null given, called in /Users/edweld/Documents/projects2017/gousto/src/App/Service/RecipeService.php on line 60 at /Users/edweld/Documents/projects2017/gousto/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:652)"} []
[2017-05-15 14:55:10] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 14:55:10] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 14:55:39] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 14:55:39] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 14:56:33] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 14:56:33] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 14:56:46] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 14:56:46] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 15:01:47] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 15:01:47] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 15:01:57] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 15:01:57] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 15:02:08] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 15:02:08] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 15:05:17] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 15:05:17] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 15:06:17] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 15:06:17] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 15:06:41] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 15:06:41] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 15:07:05] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 15:07:05] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 15:08:02] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 15:08:02] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 15:08:43] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 15:08:43] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 15:38:22] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 15:38:22] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 127 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:127)"} []
[2017-05-15 15:41:56] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 114 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:114)"} []
[2017-05-15 15:49:12] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 115 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:115)"} []
[2017-05-15 15:49:43] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 115 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:115)"} []
[2017-05-15 15:50:06] application.CRITICAL: InvalidArgumentException: Service "recipe.controller" is not callable. (uncaught exception) at /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/CallbackResolver.php line 59 {"exception":"[object] (InvalidArgumentException(code: 0): Service \"recipe.controller\" is not callable. at /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/CallbackResolver.php:59)"} []
[2017-05-15 15:50:06] application.ERROR: Service "recipe.controller" is not callable. [] []
[2017-05-15 15:50:06] application.ERROR: #0 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/ServiceControllerResolver.php(50): Silex\CallbackResolver->convertCallback('recipe.controll...') #1 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(136): Silex\ServiceControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request)) #2 /Users/edweld/Documents/projects2017/gousto/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #3 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(496): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #4 /Users/edweld/Documents/projects2017/gousto/vendor/silex/silex/src/Silex/Application.php(477): Silex\Application->handle(Object(Symfony\Component\HttpFoundation\Request)) #5 /Users/edweld/Documents/projects2017/gousto/web/index.php(19): Silex\Application->run() #6 {main} [] []
[2017-05-15 15:51:02] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 116 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:116)"} []
[2017-05-15 15:51:14] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 116 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:116)"} []
[2017-05-15 15:51:40] application.ERROR: Uncaught Exception Error: "Cannot use object of type Symfony\Component\HttpFoundation\Request as array" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 115 {"exception":"[object] (Error(code: 0): Cannot use object of type Symfony\\Component\\HttpFoundation\\Request as array at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:115)"} []
[2017-05-15 15:53:21] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 128 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:128)"} []
[2017-05-15 15:53:48] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 128 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:128)"} []
[2017-05-15 15:55:22] application.ERROR: Uncaught Exception Error: "Call to undefined method App\Service\RecipeService::fetchRating()" at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php line 128 {"exception":"[object] (Error(code: 0): Call to undefined method App\\Service\\RecipeService::fetchRating() at /Users/edweld/Documents/projects2017/gousto/src/App/Controller/RecipeController.php:128)"} []
